version: '3.3' 
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped